#!/bin/bash
ADBFASTBOOT_H3=h3
ADBFASTBOOT_M3=m3
MINICOM_H3=/dev/ttyUSB0
MINICOM_M3=/dev/ttyUSB1
PHIDGET_SERIAL_H3=1
PHIDGET_SERIAL_M3=2
#Export vars required for scripts
#% before, # after

. $SCRIPTS_DIR/check-build-params.sh
. $SCRIPTS_DIR/export-env.sh
. $SCRIPTS_DIR/set-url.sh

if [ "$HW_PLATFORM" == "full_salvator_h3" ]; then
  export FASTBOOT_SERIAL=$ADBFASTBOOT_H3
  export MINICOM_SERIAL=$MINICOM_H3
  export PHIDGET_SERIAL=$PHIDGET_SERIAL_H3
elif [ "$HW_PLATFORM" == "full_salvator_m3" ]; then
  export FASTBOOT_SERIAL=$ADBFASTBOOT_M3
  export MINICOM_SERIAL=$MINICOM_M3
  export PHIDGET_SERIAL=$PHIDGET_SERIAL_M3
elif [ "$HW_PLATFORM" == "salvator_car_h3" ]; then
  export FASTBOOT_SERIAL=$ADBFASTBOOT_H3
  export MINICOM_SERIAL=$MINICOM_H3
  export PHIDGET_SERIAL=$PHIDGET_SERIAL_H3
elif [ "$HW_PLATFORM" == "salvator_car_m3" ]; then
  export FASTBOOT_SERIAL=$ADBFASTBOOT_M3
  export MINICOM_SERIAL=$MINICOM_M3
  export PHIDGET_SERIAL=$PHIDGET_SERIAL_M3
fi

export ANDROID_SERIAL=$FASTBOOT_SERIAL
export ADB_CMD="adb"

. $SCRIPTS_DIR/create-output-dir.sh

#Print values

echo SCRIPTS_DIR=$SCRIPTS_DIR
echo BUILD_DIR=$BUILD_DIR
echo BUILD_URL=$BUILD_URL
echo FASTBOOT_SERIAL=$FASTBOOT_SERIAL
echo MINICOM_SERIAL=$MINICOM_SERIAL
echo PHIDGET_SERIAL=$PHIDGET_SERIAL
echo PATH_TO_CAPTURE_LOGS=$PATH_TO_CAPTURE_LOGS
echo OUTPUT_FILE=$OUTPUT_FILE
echo ADB_CMD=$ADB_CMD

#Exit
